### ISSUE TITLE
Failed to replicate an example with dynamic extents

### ISSUE THREAD

**Issue by weslleyspereira** [kokkos/mdspan#66]
Hi! I am developing <T>LAPACK, a library with template implementations of BLAS and LAPACK: https://github.com/tlapack/tlapack/. There is an issue there (https://github.com/tlapack/tlapack/issues/6) where we are discussing the use of mdspan as an abstraction for our multidimensional arrays.

I faild to reproduce your examples with dynamic extents. Please, see here:
https://github.com/tlapack/tlapack/blob/a11034061331343f85fbd1cac1a7af69b19e20a5/include/blas/gemv.hpp#L91-L92
and here:
https://github.com/tlapack/tlapack/blob/a11034061331343f85fbd1cac1a7af69b19e20a5/include/blas/utils.hpp#L24
https://github.com/tlapack/tlapack/blob/a11034061331343f85fbd1cac1a7af69b19e20a5/include/blas/utils.hpp#L50-L52
where I load your library (5694f21c39f3b948d06a0c63b9c219bf802e28a8).

The code doesn't compile on my Ubuntu 20.04 using GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0. The error message is:
```
[build] /home/pereiraw/storage/tlapack/include/blas/gemv.hpp:92:15: error: no matching function for call to ‘std::experimental::mdspan<float, std::experimental::extents<18446744073709551615, 18446744073709551615>, std::experimental::layout_right, std::experimental::default_accessor<float> >::mdspan(const float*&, blas::size_t&, blas::size_t&)’
[build]    92 |     auto _A = span_2d_dynamic(A, lda, n);
[build]       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

It is probably something easy to solve. I was trying to mimic the examples here:
https://github.com/kokkos/mdspan/wiki/A-Gentle-Introduction-to-mdspan
and here:
https://github.com/kokkos/mdspan/tree/stable/examples

I would appreciate some help here. Thanks!

**Comment by mhoemmen** [comment]
@weslleyspereira Hi there!  It looks like you're trying to construct a view-of-nonconst (`mdspan<float, ...>`) with a pointer-to-const (`const float*`).  You can't assign a pointer-to-const to a pointer-to-nonconst.  The fix is to use `mdspan<const float, ...>` as the matrix view type.

**Comment by weslleyspereira** [comment]
Thanks, @mhoemmen! I knew it was a pretty simple doubt. :)

**Comment by mhoemmen** [comment]
@weslleyspereira Gladly! : - )  You might find the [View section](https://github.com/kokkos/kokkos/wiki/View) of the Kokkos Programming Guide helpful background reading.  Some of that writing was my doing, a while back.  The most important difference between `mdspan` and `Kokkos::View` is that `mdspan` does not own its data, while `Kokkos::View` owns its data (by default).
